import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import React from 'react';
import {Button, Grid, Paper} from '@material-ui/core';
import Header from '../../components/Header'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.body}>
          <Grid container spacing={0}>
            <Grid align-content='left' xs={12} sm={9}>
              <h1>勉強</h1>
              <p>今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
            </Grid>
            <Grid xs={12} sm={3}>
              <h1>勉強</h1>
              <p>今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
              <h1>勉強</h1>
              <p>今日はイマイチだった</p>
            </Grid>
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
