import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import {Button, Grid} from '@material-ui/core';
import MediaCard from '../components/Card/Card';
import Header from '../components/Header';



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dairy edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} >
        <Header />
        <div className={styles.body} >
          <Grid container spacing={6}>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
                <Grid item xs={12} sm={4}>
                    <MediaCard date={'Date.now()'} text={'sample'} />
                </Grid>
            </Grid>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
